const ESPECIES = [

  {
    id:        "jaguar",
    nombre:    "Jaguar",
    cient:     "Panthera onca",
    emoji:     "🐆",
    categoria: "Mamífero · Felino",
    estado:    "VULNERABLE",          /* "EN PELIGRO CRÍTICO" | "VULNERABLE" | "AMENAZADO" */
    habitat:   "Selva tropical",
    poblacion: "~64,000 ind.",
    tamaño:    "1.1 – 1.85 m",
    peso:      "56 – 96 kg",
    sonido:    "selva",               /* "selva" | "oceano" | "lluvia" | "viento" | "cueva" */
    desc: `El jaguar es el felino más grande de América y el tercero del mundo, superado solo por el tigre y el león. Habita en selvas tropicales, manglares y pastizales desde el sur de México hasta el norte de Argentina. Adora el agua: nada con destreza y caza tortugas, peces y caimanes directamente en ríos y lagunas. Su mordida es la más poderosa entre los felinos y puede perforar el cráneo de sus presas de un solo golpe.`,
    amenazas: [
      "Deforestación masiva para ganadería y agricultura que destruye su hábitat.",
      "Caza furtiva: pieles, huesos y colmillos traficados ilegalmente.",
      "Conflicto con ganaderos que matan jaguares por depredación de ganado.",
      "Fragmentación del territorio por carreteras y expansión urbana.",
      "Cambio climático que reduce las selvas y desplaza a sus presas.",
    ],
    curiosidades: [
      { t:"El único que ruge",    txt:"Es el único felino de América con anatomía para rugir. Su rugido se escucha a kilómetros de distancia en la selva." },
      { t:"Mandíbula legendaria", txt:"Ejerce 1,500 lb/pulg² de presión — la más fuerte entre los felinos, capaz de partir un cráneo de tapir." },
      { t:"Amante del agua",      txt:"Mientras leones y tigres evitan ríos, el jaguar los busca activamente. Pesca con sus garras como lo haría un oso." },
      { t:"Nombre que da miedo",  txt:"Del tupí-guaraní 'yaguara': bestia que mata de un salto. Los amazónicos lo llaman 'señor de la noche'." },
    ],
  },

  {
    id:        "axolote",
    nombre:    "Ajolote",
    cient:     "Ambystoma mexicanum",
    emoji:     "🦎",
    categoria: "Anfibio · Salamandra",
    estado:    "EN PELIGRO CRÍTICO",
    habitat:   "Lagos de Xochimilco",
    poblacion: "< 1,000 ind.",
    tamaño:    "15 – 45 cm",
    peso:      "60 – 250 g",
    sonido:    "lluvia",
    desc: `El ajolote mexicano es una salamandra acuática endémica del lago de Xochimilco en la Ciudad de México. Es mundialmente famoso por su extraordinaria capacidad de regeneración: puede regenerar extremidades, corazón, pulmones y partes del cerebro sin dejar cicatrices. A diferencia de otras salamandras, el ajolote retiene sus características larvales toda la vida, un fenómeno llamado neotenia. Hoy se estima que quedan menos de 1,000 individuos en estado silvestre.`,
    amenazas: [
      "Contaminación severa del agua en los canales de Xochimilco.",
      "Introducción de peces exóticos como la carpa y la tilapia que los depredan.",
      "Urbanización y desecación de los canales históricos.",
      "Captura ilegal para mascotas y comercio internacional.",
      "Enfermedades fúngicas importadas por anfibios exóticos.",
    ],
    curiosidades: [
      { t:"Regeneración sobrehumana", txt:"Puede regenerar un corazón, un pulmón o partes del cerebro. Los científicos estudian su ADN para aplicarlo en medicina humana." },
      { t:"Nombre náhuatl",          txt:"'Axolotl' en náhuatl significa 'monstruo del agua'. Era sagrado para los aztecas, asociado al dios Xólotl." },
      { t:"Neotenia",                txt:"Es un adulto que mantiene forma de larva toda su vida. Sus branquias externas (las 'plumas' rosadas) son su característica más icónica." },
    ],
  },

  {
    id:        "vaquita-marina",
    nombre:    "Vaquita Marina",
    cient:     "Phocoena sinus",
    emoji:     "🐬",
    categoria: "Mamífero · Cetáceo",
    estado:    "EN PELIGRO CRÍTICO",
    habitat:   "Golfo de California",
    poblacion: "< 10 ind.",
    tamaño:    "1.2 – 1.5 m",
    peso:      "30 – 55 kg",
    sonido:    "oceano",
    desc: `La vaquita marina es el mamífero marino más pequeño y más amenazado del planeta. Endémica del norte del Golfo de California, México, se distingue por sus marcas oscuras alrededor de los ojos y la boca. Con menos de 10 individuos estimados, es la especie de cetáceo más rara del mundo y podría extinguirse en pocos años si no se actúa de inmediato.`,
    amenazas: [
      "Captura incidental en redes de enmalle ilegales usadas para pescar totoaba.",
      "Tráfico ilegal de la vejiga natatoria de la totoaba hacia China.",
      "Reducción del flujo de agua del río Colorado por presas y desvíos.",
      "Contaminación agrícola que altera su ecosistema.",
    ],
    curiosidades: [
      { t:"La más rara del mundo",   txt:"Fue descubierta en 1958. En menos de 70 años pasó de miles de individuos a menos de diez. Es el cetáceo más escaso de la historia." },
      { t:"Marsopa tropical",        txt:"Es la única marsopa del mundo que vive en aguas tropicales cálidas. Sus parientes prefieren mares fríos." },
      { t:"Cara de panda marino",    txt:"Sus manchas oscuras alrededor de ojos y boca le dan una expresión única. En inglés la llaman 'little cow of the sea'." },
    ],
  },

  {
    id:        "lobo-mexicano",
    nombre:    "Lobo Mexicano",
    cient:     "Canis lupus baileyi",
    emoji:     "🐺",
    categoria: "Mamífero · Cánido",
    estado:    "EN PELIGRO CRÍTICO",
    habitat:   "Bosques y montañas",
    poblacion: "~380 ind.",
    tamaño:    "1.2 – 1.5 m",
    peso:      "25 – 45 kg",
    sonido:    "viento",
    desc: `El lobo mexicano es la subespecie de lobo gris más pequeña y más amenazada de Norteamérica. Fue prácticamente extirpado de la naturaleza a mediados del siglo XX por programas de exterminio gubernamental. Gracias a programas de cría en cautiverio y reintroducción, hoy sobrevive en pequeñas poblaciones en la Sierra Madre Occidental de México y Arizona.`,
    amenazas: [
      "Caza y exterminio histórico por ganaderos y gobiernos.",
      "Pérdida de hábitat por deforestación y expansión agropecuaria.",
      "Conflicto con ganaderos por depredación de ganado.",
      "Baja diversidad genética por el efecto cuello de botella.",
      "Atropellamientos en carreteras que cruzan su territorio.",
    ],
    curiosidades: [
      { t:"Casi extinto dos veces", txt:"En 1976 quedaban solo 7 individuos. Un programa de rescate los capturó y crió en cautiverio. Todos los lobos mexicanos actuales descienden de esos 7." },
      { t:"Regulador del ecosistema", txt:"Su reintroducción en Arizona cambió el comportamiento de los venados, lo que permitió que los ríos y bosques se recuperaran." },
      { t:"El más pequeño",          txt:"Es el lobo más pequeño de Norteamérica. Su tamaño compacto le permite moverse en la densa vegetación de la Sierra Madre." },
    ],
  },

  {
    id:        "manatí",
    nombre:    "Manatí del Caribe",
    cient:     "Trichechus manatus",
    emoji:     "🦭",
    categoria: "Mamífero · Sirenio",
    estado:    "VULNERABLE",
    habitat:   "Costas y ríos del Caribe",
    poblacion: "~6,000 ind.",
    tamaño:    "2.5 – 4.5 m",
    peso:      "400 – 600 kg",
    sonido:    "oceano",
    desc: `El manatí del Caribe es un mamífero marino herbívoro que habita en costas, bahías, estuarios y ríos de agua cálida. Conocido como "la vaca marina" por su apacible comportamiento y dieta de plantas acuáticas, puede consumir hasta 10% de su peso corporal en vegetación al día. A pesar de su tamaño, es un nadador gracioso que puede alcanzar los 8 km/h.`,
    amenazas: [
      "Colisiones con embarcaciones de motor, la principal causa de muerte.",
      "Pérdida de hábitat por desarrollo costero y destrucción de manglares.",
      "Enredamiento en redes de pesca.",
      "Proliferación de algas tóxicas causadas por contaminación agrícola.",
      "Cambio climático que altera la temperatura del agua.",
    ],
    curiosidades: [
      { t:"Sirena del Caribe",    txt:"Los marineros del siglo XV los confundieron con sirenas. Cristóbal Colón escribió que las sirenas 'no eran tan hermosas como se decía'." },
      { t:"Prima del elefante",   txt:"A pesar de vivir en el agua, el pariente vivo más cercano del manatí es el elefante. Comparten un ancestro común de hace 60 millones de años." },
      { t:"Dientes rotatorios",   txt:"Es uno de los pocos mamíferos con dentición conveyor: los dientes se mueven hacia adelante y los viejos caen, reemplazados por nuevos desde atrás." },
    ],
  },

  {
    id:        "tapir",
    nombre:    "Tapir Centroamericano",
    cient:     "Tapirus bairdii",
    emoji:     "🦏",
    categoria: "Mamífero · Perissodáctilo",
    estado:    "EN PELIGRO CRÍTICO",
    habitat:   "Bosque húmedo tropical",
    poblacion: "< 5,500 ind.",
    tamaño:    "1.8 – 2.5 m",
    peso:      "150 – 300 kg",
    sonido:    "selva",
    desc: `El tapir centroamericano, también llamado danta o tapir de Baird, es el mamífero terrestre más grande de Mesoamérica. Es un animal solitario y nocturno que habita bosques tropicales densos. Su pequeña trompa prensil —evolución independiente a la del elefante— le permite agarrar hojas, frutos y ramas. Es un dispersor de semillas fundamental para la regeneración del bosque.`,
    amenazas: [
      "Deforestación y fragmentación del bosque tropical.",
      "Caza furtiva por su carne, considerada un manjar en algunas regiones.",
      "Atropellamientos al cruzar carreteras que dividen su hábitat.",
      "Pérdida de corredores biológicos entre poblaciones.",
    ],
    curiosidades: [
      { t:"El jardinero del bosque", txt:"Dispersa semillas grandes que ninguna otra especie puede transportar. Sin tapires, muchos árboles tropicales no podrían reproducirse." },
      { t:"Diseño antiguo",          txt:"Los tapires han mantenido casi la misma forma corporal durante 35 millones de años. Son fósiles vivientes de una era pasada." },
      { t:"Nadador experto",         txt:"Se refugian del calor y de los depredadores sumergiéndose en ríos y lagunas. Pueden caminar por el fondo como hipopótamos." },
    ],
  },

  {
    id:        "mono-arana",
    nombre:    "Mono Araña",
    cient:     "Ateles geoffroyi",
    emoji:     "🐒",
    categoria: "Mamífero · Primate",
    estado:    "EN PELIGRO CRÍTICO",
    habitat:   "Selva alta perennifolia",
    poblacion: "< 2,000 ind. (México)",
    tamaño:    "38 – 63 cm",
    peso:      "6 – 9 kg",
    sonido:    "selva",
    desc: `El mono araña geoffroy es uno de los primates más inteligentes de América. Vive en las selvas altas de México y Centroamérica en grupos sociales complejos liderados por hembras. Su larga cola prensil actúa como un quinto miembro que le permite desplazarse ágilmente por el dosel del bosque. Es un dispersor de semillas crítico para la biodiversidad de la selva.`,
    amenazas: [
      "Deforestación masiva de la selva alta en México y Centroamérica.",
      "Cacería furtiva para alimento o captura como mascota.",
      "Baja tasa reproductiva: una cría cada 2-3 años.",
      "Fragmentación del hábitat que aísla poblaciones pequeñas.",
    ],
    curiosidades: [
      { t:"Cola de agarre",        txt:"Su cola prensil es tan fuerte que puede sostener su peso corporal completo. La usan como tercera mano para tomar frutos." },
      { t:"Memoria de árbol",      txt:"Recuerdan la ubicación de cientos de árboles frutales y planifican rutas según la temporada. Su inteligencia espacial rivaliza con la de los chimpancés." },
      { t:"Sociedades matriarcales", txt:"Las hembras lideran el grupo y deciden los movimientos. Los machos jóvenes emigran a otros grupos para evitar la consanguinidad." },
    ],
  },

  {
    id:        "ocelote",
    nombre:    "Ocelote",
    cient:     "Leopardus pardalis",
    emoji:     "🐱",
    categoria: "Mamífero · Felino",
    estado:    "VULNERABLE",
    habitat:   "Selva tropical y subtropical",
    poblacion: "~40,000 ind.",
    tamaño:    "55 – 100 cm",
    peso:      "8 – 16 kg",
    sonido:    "selva",
    desc: `El ocelote es uno de los felinos más hermosos del continente americano. Su pelaje manchado de rosetas lo hace inconfundible, aunque también lo ha convertido en blanco de cazadores de pieles durante siglos. Cazador nocturno experto, puede trepar árboles y nadar con facilidad. Habita desde el sur de Texas hasta el norte de Argentina.`,
    amenazas: [
      "Histórica caza masiva por su piel, que diezmó las poblaciones en el siglo XX.",
      "Pérdida de hábitat por deforestación y expansión agrícola.",
      "Atropellamientos en carreteras dentro de su territorio.",
      "Captura para el comercio ilegal de mascotas exóticas.",
    ],
    curiosidades: [
      { t:"El felino de la moda",  txt:"En los años 60 y 70 se mataban hasta 200,000 ocelotes al año solo para hacer abrigos de piel. Hoy está prohibido internacionalmente." },
      { t:"Visión nocturna",       txt:"Sus ojos tienen seis veces más células de luz que los humanos, lo que le permite cazar en casi total oscuridad." },
      { t:"Cazador versátil",      txt:"Puede cazar presas en el suelo, en los árboles o en el agua. Su menú incluye desde ratones hasta iguanas y peces." },
    ],
  },

  {
    id:        "nutria",
    nombre:    "Nutria de Río",
    cient:     "Lontra longicaudis",
    emoji:     "🦦",
    categoria: "Mamífero · Mustélido",
    estado:    "AMENAZADO",
    habitat:   "Ríos y humedales",
    poblacion: "Desconocida (en declive)",
    tamaño:    "45 – 73 cm",
    peso:      "5 – 14 kg",
    sonido:    "lluvia",
    desc: `La nutria neotropical habita ríos, lagunas y humedales desde México hasta Argentina. Es un indicador clave de la salud de los ecosistemas acuáticos: si hay nutrias, el río está sano. Cazadora ágil, puede mantenerse bajo el agua hasta 4 minutos y es capaz de capturar peces, crustáceos y hasta pequeños caimanes.`,
    amenazas: [
      "Caza histórica por su densa y valiosa piel.",
      "Contaminación de ríos por agroquímicos y metales pesados.",
      "Construcción de represas que fragmenta y destruye su hábitat.",
      "Disminución de presas por sobrepesca en los ríos.",
    ],
    curiosidades: [
      { t:"El guardián del río",   txt:"Su presencia indica aguas limpias y ecosistemas saludables. Los biólogos la usan como especie indicadora para monitorear la salud fluvial." },
      { t:"Juguetona por naturaleza", txt:"Las nutrias adultas siguen jugando toda su vida: se deslizan por barros y nadan en espirales sin ningún propósito más que el disfrute." },
      { t:"Comunicación rica",     txt:"Producen al menos 22 sonidos diferentes para comunicarse con su familia, desde gorjeos hasta chirridos de alarma." },
    ],
  },

  {
    id:        "murcielago-nariz-larga",
    nombre:    "Murciélago Nariz Larga",
    cient:     "Leptonycteris nivalis",
    emoji:     "🦇",
    categoria: "Mamífero · Quiróptero",
    estado:    "EN PELIGRO CRÍTICO",
    habitat:   "Cuevas y desierto",
    poblacion: "< 10,000 ind.",
    tamaño:    "7 – 9 cm",
    peso:      "18 – 30 g",
    sonido:    "cueva",
    desc: `El murciélago nariz larga mayor es un polinizador nocturno crítico para el desierto mexicano. Migra cientos de kilómetros siguiendo la floración de agaves, cactus y otras plantas. Sin él, muchas especies de agave —incluidas las que producen mezcal y tequila— no podrían reproducirse. Es el principal polinizador del agave silvestre.`,
    amenazas: [
      "Perturbación y destrucción de cuevas utilizadas como colonias de maternidad.",
      "Expansión de agaves cosechados antes de florecer, eliminando su fuente de alimento.",
      "Persecución por temor injustificado hacia los murciélagos.",
      "Uso de pesticidas que envenenan los insectos y flores de los que se alimenta.",
    ],
    curiosidades: [
      { t:"El padre del tequila",   txt:"Poliniza el agave azul silvestre. Sin murciélagos nariz larga, la industria del tequila y el mezcal no existiría como la conocemos." },
      { t:"Migrante nocturno",      txt:"Viaja hasta 150 km en una noche siguiendo el rastro de flores. Su ruta migratoria coincide exactamente con la floración del agave." },
      { t:"Echolocalización fina",  txt:"Emite pulsos ultrasónicos tan precisos que puede detectar una flor abierta entre cientos de flores cerradas en la oscuridad total." },
    ],
  },

  /* ── AVES ─────────────────────────────────────────────── */
  {
    id:        "quetzal",
    nombre:    "Quetzal",
    cient:     "Pharomachrus mocinno",
    emoji:     "🦜",
    categoria: "Ave · Trogon",
    estado:    "AMENAZADO",
    habitat:   "Bosque nublado",
    poblacion: "< 50,000 ind.",
    tamaño:    "35 – 40 cm (+60 cm cola)",
    peso:      "180 – 210 g",
    sonido:    "selva",
    desc: `El quetzal resplandeciente es considerado una de las aves más hermosas del mundo. Los mayas y aztecas lo consideraban sagrado y divino; sus plumas verdes iridiscentes eran más valiosas que el oro. Habita en los bosques nublados de las montañas de México y Centroamérica entre 1,200 y 3,000 metros de altitud. Es el ave nacional de Guatemala.`,
    amenazas: [
      "Deforestación de los bosques nublados de altura para agricultura y ganadería.",
      "Fragmentación del hábitat que aísla las poblaciones reproductoras.",
      "Captura ilegal para coleccionistas y comercio de aves exóticas.",
      "Cambio climático que desplaza la zona de niebla hacia cotas más altas.",
    ],
    curiosidades: [
      { t:"Ave de la libertad",   txt:"Los mayas creían que el quetzal moriría de pena si era enjaulado. Por eso nunca lo capturaban, solo tomaban sus plumas y lo liberaban." },
      { t:"Cola de novio",        txt:"Los machos desarrollan plumas de cola de hasta 90 cm solo durante la época de cría. Las usan para impresionar a las hembras en vuelos acrobáticos." },
      { t:"Cultivador de bosques", txt:"Dispersa las semillas del aguacate silvestre. Sin quetzales, este árbol sagrado de los mayas no podría regenerarse en las montañas." },
    ],
  },

  {
    id:        "aguila-real",
    nombre:    "Águila Real",
    cient:     "Aquila chrysaetos",
    emoji:     "🦅",
    categoria: "Ave · Rapaz",
    estado:    "AMENAZADO",
    habitat:   "Montañas y barrancas",
    poblacion: "< 2,000 ind. (México)",
    tamaño:    "76 – 102 cm",
    peso:      "3 – 6.3 kg",
    sonido:    "viento",
    desc: `El águila real es el símbolo nacional de México y aparece en el escudo nacional. Es el ave rapaz más grande de Norteamérica y uno de los cazadores aéreos más poderosos del mundo. Puede alcanzar los 320 km/h en picada. Vive en parejas monógamas de por vida y usa el mismo nido —que renueva año tras año— durante décadas.`,
    amenazas: [
      "Persecución directa por ganaderos que temen la depredación de ganado.",
      "Envenenamiento secundario por consumir presas intoxicadas con pesticidas.",
      "Pérdida de territorio por expansión urbana y agrícola en montañas.",
      "Electrocución en tendidos eléctricos de alta tensión.",
      "Tráfico ilegal de polluelos para cetrería.",
    ],
    curiosidades: [
      { t:"Velocidad de picada",   txt:"En picada puede superar los 320 km/h, siendo uno de los animales más rápidos de la Tierra en movimiento horizontal." },
      { t:"Nidos históricos",      txt:"Los nidos, llamados 'eyries', se amplifican cada año. Algunos tienen más de 100 años y pueden pesar hasta una tonelada." },
      { t:"Visión de águila",      txt:"Ve hasta 8 veces más nítido que un humano y puede detectar un conejo a 3 km de distancia desde el aire." },
    ],
  },

  {
    id:        "condor-california",
    nombre:    "Cóndor de California",
    cient:     "Gymnogyps californianus",
    emoji:     "🦅",
    categoria: "Ave · Buitre del Nuevo Mundo",
    estado:    "EN PELIGRO CRÍTICO",
    habitat:   "Acantilados y montañas",
    poblacion: "~500 ind.",
    tamaño:    "109 – 140 cm",
    peso:      "7 – 14 kg",
    sonido:    "viento",
    desc: `El cóndor de California es el ave voladora más grande de Norteamérica, con una envergadura de hasta 3 metros. En 1987, los últimos 27 individuos fueron capturados para evitar su extinción. Gracias a un programa de reproducción en cautiverio, hoy existen más de 500. Es uno de los mayores éxitos de conservación de la historia, aunque sigue en peligro crítico.`,
    amenazas: [
      "Envenenamiento por plomo: ingieren balas de plomo al comer carroña.",
      "Colisiones con tendidos eléctricos y líneas de alta tensión.",
      "Ingestión de microplásticos y basura que alimentan a sus polluelos.",
      "Baja reproducción: solo un huevo cada dos años por pareja.",
    ],
    curiosidades: [
      { t:"Rescate épico de 1987",  txt:"Los últimos 27 cóndores salvajes fueron capturados en una operación de rescate. Parecía el fin. Hoy son más de 500 gracias a ese acto desesperado." },
      { t:"Envergadura récord",     txt:"Con alas de hasta 3 metros, es el ave voladora más grande de Norteamérica. Puede planear durante horas sin mover las alas." },
      { t:"Detector de carroña",    txt:"No tiene sentido del olfato. Localiza carroña observando el comportamiento de otros buitres que sí pueden olerla desde kilómetros." },
    ],
  },

  {
    id:        "guacamayo-escarlata",
    nombre:    "Guacamayo Escarlata",
    cient:     "Ara macao",
    emoji:     "🦜",
    categoria: "Ave · Psitácido",
    estado:    "AMENAZADO",
    habitat:   "Selva húmeda tropical",
    poblacion: "~20,000 ind. (México)",
    tamaño:    "81 – 96 cm",
    peso:      "900 – 1,100 g",
    sonido:    "selva",
    desc: `El guacamayo escarlata es una de las aves más coloridas y carismáticas de México. Vive en parejas permanentes toda su vida y son conocidos por su fidelidad. Inteligente y longevo, puede vivir hasta 75 años. En México fue eliminado de gran parte de su rango histórico; hoy solo sobrevive en la Reserva de la Biósfera El Triunfo en Chiapas y en la costa de Oaxaca.`,
    amenazas: [
      "Captura ilegal masiva para el comercio de aves exóticas.",
      "Deforestación de las selvas húmedas donde anida en árboles huecos.",
      "Destrucción de sitios de anidación por tala selectiva.",
      "Caza histórica por sus plumas para adornos y rituales.",
    ],
    curiosidades: [
      { t:"De por vida",           txt:"Las parejas de guacamayos se mantienen unidas toda la vida. Si uno muere, el sobreviviente puede caer en un estado de duelo observable." },
      { t:"Inteligencia de niño",  txt:"Su inteligencia es comparable a la de un niño de 4 años. Pueden resolver puzzles, imitar voces y usar herramientas simples." },
      { t:"Memoria de ubicación",  txt:"Recuerdan la ubicación exacta de cientos de árboles frutales y los visitan en el momento óptimo de maduración." },
    ],
  },

  /* ── REPTILES Y ANFIBIOS ────────────────────────────── */
  {
    id:        "tortuga-laud",
    nombre:    "Tortuga Laúd",
    cient:     "Dermochelys coriacea",
    emoji:     "🐢",
    categoria: "Reptil · Tortuga marina",
    estado:    "VULNERABLE",
    habitat:   "Océanos tropicales",
    poblacion: "< 35,000 hembras",
    tamaño:    "1.3 – 1.8 m",
    peso:      "250 – 900 kg",
    sonido:    "oceano",
    desc: `La tortuga laúd es el reptil más grande del mundo y el más grande de las tortugas. A diferencia de otras tortugas marinas, no tiene caparazón duro sino una coraza de piel flexible y cartilaginosa. Puede bucear hasta 1,280 metros de profundidad y tolerar aguas frías gracias a un sistema circulatorio único. Regresa cada año a la misma playa donde nació para anidar.`,
    amenazas: [
      "Captura incidental en redes de pesca de palangre y arrastre.",
      "Recolección ilegal de huevos en playas de anidación.",
      "Ingestión de bolsas plásticas que confunden con medusas, su alimento principal.",
      "Iluminación artificial en playas que desorienta a las crías recién nacidas.",
      "Cambio climático que altera la temperatura de las playas de anidación.",
    ],
    curiosidades: [
      { t:"El reptil más grande",   txt:"Puede pesar hasta 900 kg y medir 1.8 m. El ejemplar más grande registrado pesó 916 kg." },
      { t:"Buzo récord",            txt:"Puede bucear hasta 1,280 metros de profundidad, más que cualquier otro reptil. En una sola inmersión puede durar 85 minutos bajo el agua." },
      { t:"GPS viviente",           txt:"Regresa exactamente a la playa donde nació para poner sus huevos, aunque hayan pasado 30 años. Usa el campo magnético de la Tierra como brújula." },
    ],
  },

  {
    id:        "tortuga-caguama",
    nombre:    "Tortuga Caguama",
    cient:     "Caretta caretta",
    emoji:     "🐢",
    categoria: "Reptil · Tortuga marina",
    estado:    "VULNERABLE",
    habitat:   "Océano Atlántico y Pacífico",
    poblacion: "~50,000 hembras",
    tamaño:    "70 – 95 cm",
    peso:      "80 – 200 kg",
    sonido:    "oceano",
    desc: `La tortuga caguama es conocida por su enorme cabeza y su poderosa mandíbula, capaz de triturar conchas de cangrejos y moluscos. Realiza migraciones de miles de kilómetros entre sus zonas de alimentación y sus playas de anidación. Una hembra puede poner hasta 5 nidadas por temporada, con unos 100 huevos cada una.`,
    amenazas: [
      "Captura incidental en redes de arrastre y palangre.",
      "Contaminación plástica y petróleo en océanos.",
      "Destrucción y urbanización de playas de anidación.",
      "Colisiones con embarcaciones de motor.",
      "Recolección ilegal de huevos y caza de adultos.",
    ],
    curiosidades: [
      { t:"La cabeza más grande",   txt:"Su cráneo enorme —de hasta 25 cm de ancho— alberga músculos mandibulares tan poderosos que pueden triturar un cangrejo herradura." },
      { t:"Migraciones épicas",     txt:"Una hembra marcada viajó 12,000 km desde Indonesia hasta las costas de Baja California para anidar. El viaje de ida y vuelta tarda tres años." },
      { t:"Temperatura determina sexo", txt:"El calor del nido decide si los huevos se convierten en machos o hembras. El calentamiento global está produciendo más hembras, desequilibrando la población." },
    ],
  },

  {
    id:        "cocodrilo-americano",
    nombre:    "Cocodrilo Americano",
    cient:     "Crocodylus acutus",
    emoji:     "🐊",
    categoria: "Reptil · Crocodiliano",
    estado:    "VULNERABLE",
    habitat:   "Manglares y estuarios",
    poblacion: "< 2,000 ind. (México)",
    tamaño:    "3 – 5 m",
    peso:      "180 – 450 kg",
    sonido:    "oceano",
    desc: `El cocodrilo americano es el mayor depredador de los humedales costeros de México. A diferencia del cocodrilo de pantano (Crocodylus moreletii), el americano tolera la sal y habita manglares, estuarios y bahías. Es un ingeniero del ecosistema: sus madrigueras crean refugios para otras especies durante las sequías.`,
    amenazas: [
      "Caza histórica masiva por su piel para la industria de la moda.",
      "Destrucción de manglares para desarrollos turísticos y camaroneras.",
      "Matanza por represalia al considerarse amenaza para humanos y ganado.",
      "Captura de juveniles para granjas de cocodrilos ilegales.",
    ],
    curiosidades: [
      { t:"Dinosaurio moderno",    txt:"Los cocodrilos han mantenido casi la misma forma durante 80 millones de años. Sobrevivieron la extinción que mató a los dinosaurios." },
      { t:"Padre del año",         txt:"Contrario a su imagen feroz, los cocodrilos son padres devotos. El macho guarda el nido y la hembra transporta gentilmente a las crías en su boca hasta el agua." },
      { t:"Termómetro del pantano", txt:"Sus madrigueras retienen agua durante las sequías, creando oasis donde beben y viven decenas de otras especies. Sin cocodrilos, el humedal colapsa." },
    ],
  },

  /* ── PECES Y MARINOS ────────────────────────────────── */
  {
    id:        "totoaba",
    nombre:    "Totoaba",
    cient:     "Totoaba macdonaldi",
    emoji:     "🐟",
    categoria: "Pez · Esciénido",
    estado:    "EN PELIGRO CRÍTICO",
    habitat:   "Golfo de California",
    poblacion: "Desconocida (crítica)",
    tamaño:    "hasta 2 m",
    peso:      "hasta 100 kg",
    sonido:    "oceano",
    desc: `La totoaba es el pez esciénido más grande del mundo y endémico del Golfo de California. Su vejiga natatoria, llamada "el oro blanco del mar", se vende en el mercado negro chino por más de 20,000 dólares el kilogramo. La pesca ilegal de totoaba con redes de enmalle es también la principal causa de muerte de la vaquita marina.`,
    amenazas: [
      "Pesca ilegal masiva impulsada por el altísimo precio de su vejiga natatoria.",
      "Redes de enmalle que atrapan incidentalmente a la vaquita marina.",
      "Reducción del flujo del río Colorado que alteró su ecosistema de reproducción.",
      "Sobrepesca histórica que colapsó la población en los años 70.",
    ],
    curiosidades: [
      { t:"El oro blanco del mar", txt:"Su vejiga natatoria seca vale más que la cocaína en el mercado negro chino, donde se usa en medicina tradicional. Un kilo puede superar los 20,000 dólares." },
      { t:"Canto submarino",       txt:"Produce sonidos tan fuertes durante el apareamiento que los pescadores históricos podían escucharlos desde la orilla sin sumergirse." },
      { t:"Doble víctima",         txt:"La pesca ilegal de totoaba usa redes que atrapan accidentalmente a la vaquita marina. Una especie amenazada está matando a otra especie amenazada." },
    ],
  },

  {
    id:        "tiburon-ballena",
    nombre:    "Tiburón Ballena",
    cient:     "Rhincodon typus",
    emoji:     "🦈",
    categoria: "Pez · Elasmobranquio",
    estado:    "AMENAZADO",
    habitat:   "Mares tropicales y templados",
    poblacion: "Desconocida (en declive)",
    tamaño:    "5.5 – 12 m",
    peso:      "hasta 21 toneladas",
    sonido:    "oceano",
    desc: `El tiburón ballena es el pez más grande del mundo. A pesar de su imponente tamaño, es completamente inofensivo para los humanos: se alimenta de plancton, krill y pequeños peces filtrando el agua con su enorme boca. Puede vivir hasta 150 años y realiza migraciones de miles de kilómetros. El Mar de Cortés en México es uno de sus sitios de alimentación más importantes del planeta.`,
    amenazas: [
      "Captura directa en Asia para consumo de su carne y aletas.",
      "Colisiones con embarcaciones de motor en rutas migratorias.",
      "Captura incidental en redes de arrastre.",
      "Turismo irresponsable que perturba su comportamiento.",
      "Reducción del plancton por el calentamiento del océano.",
    ],
    curiosidades: [
      { t:"El pez más grande",     txt:"El ejemplar más grande medido tenía 18.8 metros y pesaba 21 toneladas. Su boca puede abrir hasta 1.5 metros de ancho." },
      { t:"Filtro viviente",       txt:"Filtra hasta 6,000 litros de agua por hora para extraer su alimento. En un día puede consumir 21 kilogramos de plancton." },
      { t:"Constelación de puntos", txt:"Cada tiburón ballena tiene un patrón único de puntos blancos, como huellas digitales. Los científicos los identifican individualmente con software astronómico." },
    ],
  },

  /* ── FLORA E INSECTOS ───────────────────────────────── */
  {
    id:        "mariposa-monarca",
    nombre:    "Mariposa Monarca",
    cient:     "Danaus plexippus",
    emoji:     "🦋",
    categoria: "Insecto · Lepidóptero",
    estado:    "EN PELIGRO CRÍTICO",
    habitat:   "Bosques de oyamel, México",
    poblacion: "En fuerte declive",
    tamaño:    "8.9 – 10.2 cm (envergadura)",
    peso:      "< 1 g",
    sonido:    "selva",
    desc: `La mariposa monarca realiza una de las migraciones más extraordinarias de la naturaleza: viaja hasta 4,800 km desde Canadá y EE. UU. hasta los bosques de oyamel de Michoacán y Estado de México. Millones de mariposas cubren los árboles creando una alfombra naranja viva. En invierno de 2022, la población que hibernó en México cayó un 26% respecto al año anterior.`,
    amenazas: [
      "Pérdida de bosques de oyamel en México por tala ilegal y cambio climático.",
      "Desaparición del algodoncillo (Asclepias) en EE. UU. y Canadá por herbicidas.",
      "Eventos climáticos extremos que matan millones durante la migración.",
      "Deforestación de hábitats de verano en Norteamérica.",
    ],
    curiosidades: [
      { t:"Navegación solar",      txt:"Usan el sol como brújula y compensan su movimiento con un reloj biológico interno. También detectan el campo magnético terrestre." },
      { t:"La generación milagro", txt:"La generación que migra a México vive 8 meses (las otras solo 6 semanas). Nadie sabe cómo 'saben' que tienen que vivir más tiempo." },
      { t:"Veneno decorativo",     txt:"Son tóxicas para los pájaros porque las orugas comen algodoncillo venenoso. Su color naranja brillante avisa: 'no me comas'." },
    ],
  },

  {
    id:        "orquidea-monja",
    nombre:    "Orquídea Monja Blanca",
    cient:     "Lycaste skinneri",
    emoji:     "🌸",
    categoria: "Planta · Orquidácea",
    estado:    "EN PELIGRO CRÍTICO",
    habitat:   "Bosque nublado de Guatemala y Chiapas",
    poblacion: "< 3,000 ind. silvestres",
    tamaño:    "10 – 15 cm (flor)",
    peso:      "—",
    sonido:    "selva",
    desc: `La orquídea monja blanca es la flor nacional de Guatemala y una de las orquídeas más hermosas del mundo. Sus flores blancas con tonos rosados, que pueden durar semanas, la convirtieron en objetivo de coleccionistas desde el siglo XIX. Crece en los bosques nublados entre 1,500 y 2,500 metros de altitud, donde la humedad es constante y los árboles están cubiertos de musgo.`,
    amenazas: [
      "Extracción masiva del siglo XIX y XX que diezmó las poblaciones silvestres.",
      "Deforestación de los bosques nublados donde crece como epífita.",
      "Recolección ilegal continua a pesar de estar protegida internacionalmente.",
      "Cambio climático que desplaza la zona de niebla hacia cotas más altas.",
    ],
    curiosidades: [
      { t:"Robada por imperios",   txt:"En el siglo XIX, coleccionistas europeos enviaban expediciones a Centroamérica que extraían miles de plantas. La mayoría moría en el transporte." },
      { t:"Flor que dura semanas", txt:"Sus flores permanecen frescas durante 3 a 4 semanas en la planta, un récord entre las orquídeas. Por eso era tan codiciada para arreglos florales." },
      { t:"Epífita, no parásita",  txt:"Crece sobre los árboles pero no les hace daño. Obtiene nutrientes del aire, la lluvia y la materia orgánica que se acumula en la corteza." },
    ],
  },

{
    id: "zorrillo-rayado",
    nombre: "Zorrillo Rayado",
    cient: "Mephitis mephitis",
    emoji: "🦨",
    categoria: "Mamífero · Mephitidae",
    estado: "AMENAZADO",
    habitat: "Bosques, praderas y zonas rurales",
    poblacion: "Estable pero vulnerable a atropellamientos",
    tamaño: "50 – 80 cm",
    peso: "1 – 4 kg",
    sonido: "viento",
    desc: "Famoso por su eficaz mecanismo de defensa: un almizcle fétido que puede lanzar con gran precisión. Sus rayas blancas son una señal de advertencia para que nadie se le acerque.",
    amenazas: [
      "Atropellamientos masivos en carreteras durante sus búsquedas nocturnas.",
      "Enfermedades transmitidas por perros domésticos como la rabia.",
      "Persecución humana por el olor que emite cuando se defiende."
    ],
    curiosidades: [
      { t: "Puntería", txt: "Puede lanzar su líquido fétido hasta a 3 metros de distancia con precisión quirúrgica." },
      { t: "Baile", txt: "Antes de disparar, hace un pequeño 'baile' golpeando el suelo para avisar." }
    ],
  }

  // ─── PUEDES CONTINUAR AGREGANDO ESPECIES AQUÍ ───────────
  // Copia el bloque de arriba, cambia los datos y pega.
  // El catálogo y la página de especie se actualizan solos.

];

/* No edites nada debajo de esta línea */
if(typeof module !== 'undefined') module.exports = ESPECIES;
